### ISSUE TITLE
Created project doesn't build in AppCode

### ISSUE THREAD

**Issue by Antowkos** [artemnovichkov/swift-project-template#1]
Just create project via this template and try to build it on simulator in AppCode. Build will be failed. After small investigations I found out that fail happens because of 
```
The following build commands failed:
	Check dependencies
```

**Comment by artemnovichkov** [comment]
@Antowkos thank you for the issue, I'll try to find a problem. Stay in touch!

**Comment by artemnovichkov** [comment]
Your problems related to code signing. I tried to create an empty project in Xcode, and it builded in AppCode successfully. Did you try to set up code signing for Debug/Release?

**Comment by Antowkos** [comment]
Yes, empty project created by Xcode is fine, but project created from template isn't. 
I've tried to run my project from simulator, code signing isn't necessary for it, so I'm pretty sure it isn't code signing issue, but I will test it tomorrow and let you know.
Also, logs says that build commands failed at check dependencies stage.

**Comment by Antowkos** [comment]
@artemnovichkov, as I promise, I've tried to set up code signing, but no luck with building project.

**Comment by artemnovichkov** [comment]
Hi, @Antowkos! Sorry for long answer, I was on vacation. I've fixed your issue with updating path to project in `project.xcworkspace` file. Please let me know when you'd check it and I'll close the issue. Hope it'll help you. Thank you for contributing!
