### ISSUE TITLE
Remove settings.yml

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/swift-project-template#18]
Delete `settings.yml` configuration, because bots don't work with private repos.

**Comment by Jpfonseca** [comment]
just saw this issue can i Help ? What do you mean by remove the file ?
Add it to a `.gitignore`, so it's not committed by mistake ?

**Comment by aldocano** [comment]
#19

**Comment by artemnovichkov** [comment]
Hi, @Jpfonseca! I've already merged needed changes, but you can select another. #16, for example.
