### ISSUE TITLE
Carthage is an undocumented dependency

### ISSUE THREAD

**Issue by caipre** [artemnovichkov/swift-project-template#2]
Running cookiecutter failed for me:

```
Initialized empty Git repository in ...
/var/folders/yd/38lbvn4x4d52x1jxtk2q5lf40000gn/T/tmpHfaQHP.sh: line 6: carthage: command not found
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 127)
```

Resolved by running `brew install carthage`.

**Comment by artemnovichkov** [comment]
Hi, @caipre! cookiecutter runs post_gen_project hook which contains Carthage installation in my template , because we use it in iOS projects by defaults. If you want to fix it for further using, just remove `carthage update --no-use-binaries --platform iOS` from `hooks/post_gen_project.sh` script.

**Comment by caipre** [comment]
Hey @artemnovichkov -- I only meant that it should be documented. Would you accept a PR?
