### ISSUE TITLE
Add project name to scheme names

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/swift-project-template#39]
There are some schemes with names like "Adhoc Debug" or "AppStore". The names are used for archive names. Please append a project name, for example, "MyProject AppStore".

**Comment by TheCodeTalker** [comment]
I will take this give a pr 👍

**Comment by artemnovichkov** [comment]
Good, @TheCodeTalker, thank you!

**Comment by TheCodeTalker** [comment]
any lead where i have to look?

**Comment by TheCodeTalker** [comment]
when i am running   `carthage bootstrap --platform iOS`  in this dir `/Users/thecodetalker/Documents/swift/swift-project-template/{{ cookiecutter.name }}` it giving `*** No Cartfile.resolved found, updating dependencies`

**Comment by artemnovichkov** [comment]
All schemes are here: https://github.com/artemnovichkov/swift-project-template/tree/master/%7B%7B%20cookiecutter.name%20%7D%7D/%7B%7B%20cookiecutter.name%20%7D%7D.xcodeproj/xcshareddata/xcschemes
And you should update the xcodeproj file as well.

**Comment by TheCodeTalker** [comment]
i am getting this when i am try to open it how to update or with out open i need to change if so then how can i see the file  
<img width="424" alt="screenshot 2018-10-03 at 2 13 04 pm" src="https://user-images.githubusercontent.com/3683673/46399826-7f139d80-c716-11e8-9a1f-60675e9bf7a2.png">

**Comment by artemnovichkov** [comment]
You should open {{ cookiecutter.name }}.xcodeproj/project.pbxproj in any text editor and edit it manually.

**Comment by TheCodeTalker** [comment]
> You should open {{ cookiecutter.name }}.xcodeproj/project.pbxproj in any text editor and edit it manually.

got i will give pr in this week

**Comment by artemnovichkov** [comment]
Hi, @TheCodeTalker! I have implemented this task.
