### ISSUE TITLE
Create a project and script for template updating

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/swift-project-template#44]
It's hard to update the template. I have to create a new project, make needed changes and copy diffs to the template. I want to create a base project and a Swift script, for example https://github.com/Raizlabs/ios-template.

**Comment by alphatroya** [comment]
I use [XcodeGen](https://github.com/yonaskolb/XcodeGen) tool for the project updating. Project settings are stored in separate yaml file and there are no any xcodeproj files in the template. All generation proceed in the post-commit hook.

**Comment by artemnovichkov** [comment]
@alphatroya, thanks for the advice! Do you have an example of your template? I saw XcodeGen but I'm not sure it has all needed configuration, for instance, schemes, build phase scripts etc. I need to check it.

**Comment by alphatroya** [comment]
You can watch my early concept https://github.com/alphatroya/swift-project-template. XcodeGen has the support of schemes, targets, and configurations, even Carthage dependencies.
